"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["h1[_ngcontent-%COMP%] {\r\n  color: darkblue;\r\n}\r\n\r\na[_ngcontent-%COMP%] {\r\n  font-size: 20px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=app.component.scss.shim.ngstyle.js.map